---
name: Application CI Pipeline on Push
env:
  CONTAINER_IMAGE: deepakjotwani/sample1
on:
  push:
    branches: [master]
jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build and tag docker image
#       run: |
#         docker build . -t ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}

#     - name: Publish docker image to dockerhub
#       run: docker push ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}

    - name: Cloning Receiver Repo
      run: git clone "https://$GITHUB_TOKEN@github.com/deepakjotwani/receiver.git"

    - name: Update tag in hatchery
      run: |
            git config --global user.email "dpkjotwani12@gmail.com"
            git config --global user.name "deepakjotwani"
            git checkout -b feature/Updating-tag-sample1-ms-${GITHUB_SHA::7}
            docker run -v $GITHUB_WORKSPACE/receiver/Services/base/kustomization.yaml:/app/kustomization.yaml k8s.gcr.io/kustomize/kustomize:v3.8.7 edit set image sample1-image=${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}
            git diff --exit-code && echo 'Already deployed' || (git commit -am "Upgrade docker tag of sample1-service to ${GITHUB_SHA::7}")
            git push --set-upstream origin feature/Updating-tag-sample1-ms-${GITHUB_SHA::7}
#            hub pull-request -m "feat:Updating tag for Sample service" -b master -h feature/Updating-tag-sample1-ms-$GITHUB_SHA
      working-directory: receiver
