---
name: Application CI Pipeline on Push
env:
  CONTAINER_IMAGE: deepakjotwani/sample1
on:
  push:
    branches: [develop]
jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and tag docker image
      run: |
        docker build . -t ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}

    - name: Publish docker image to dockerhub
      run: docker push ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}
